### ISSUE TITLE
Scrolling="no" setting is hiding essential controls for some users

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-requests#492] opened 2016-02-03 20:39 UTC
We turned off scrolling on the iframe to prevent the bouncy behaviour (when the scrollbar pulses on and off). But some browsers are not resizing the window correctly, and are cutting off the bottom portion of the form. This often includes the Submit button... so the patron isn't able to send the request at all. 

Report in SW-1587 of cutting off the bottom of the calendar:
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
Viewport: width:1173 height:811

Same thing on iPhone in Safari and Chrome:

![img_2460](https://cloud.githubusercontent.com/assets/6945691/12796335/0d793bf0-ca73-11e5-94ee-a883db84745e.PNG)

![img_2461](https://cloud.githubusercontent.com/assets/6945691/12796339/1400783a-ca73-11e5-99f6-890eec19bdec.PNG)

**Comment by jvine** [comment] 2016-09-12 21:00
See also SW-1610

**Comment by ndushay** [comment] 2016-10-26 18:55
Is this the same as "Modal Resizing" from our top five goals?  Marking this as high-priority.

I experience this behavior when coming from SW using Firefox on Mac.

**Comment by jkeck** [comment] 2016-10-26 19:05
@ndushay yeah.

**Comment by jkeck** [comment] 2016-10-26 22:03
A couple of issues that we might want to tackle to solve the various issues around this.

- [ ] Position the calendar above the date-field input (because the overlay will never change the height of the container)
- [ ] Allow for a scroll bar (or a default height) to be set if we can identify that we're not in the requests app anymore (lack of postMessage?).  This will allow the WebAuth form to be completely visible.
- [ ] Figure out other height related issues (once we can reliably reproduce them)

**Comment by jkeck** [comment] 2016-11-16 19:10
Last issue has been moved to #662

**Closed** 2016-11-16 19:10 UTC
Labels: High Priority, usability
