### ISSUE TITLE
Make name and email required for all mediated requests when users use Library ID option

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/sul-requests#779] opened 2018-09-21 02:18 UTC
Make name and email required in request form for all libraries that have mediated requests. 

Original request in JIRA ticket below is from Spec because they want to have name and email recorded in request dashboard for users that complete the request using Library ID.

https://jirasul.stanford.edu/jira/browse/SW-1843

**Comment by jkeck** [comment] 2018-09-21 16:41
Will this apply to only Special Collection's requests or all requests?

**Comment by ahafele** [comment] 2018-09-21 19:13
Per JV - Everyone who gets mediated requests

**Comment by saseestone** [comment] 2018-09-24 23:33
@jkeck and @ahafele - Jennifer and I are doing some analysis work on this one.  (Trying to determine if we also need some help text to help the user understand how to input a valid Library ID - and then use this text throughout the REQ app.)

**Comment by cbeer** [comment] 2019-10-15 17:55
Duplicate of https://github.com/sul-dlss/sul-requests/issues/895.

**Closed by cbeer** 2019-10-15 17:55 UTC
Labels: analysis-needed
